### PR TITLE
improve the codes with np.meshgrid

### PR DESCRIPTION
**Pull request by Freakwill**
Mainly improve the codes, replacing the statements `np.dot(..., np.ones(...))` with function `np.meshgrid`. 
It speeds up the codes and makes them readable and _pythonic_.

`fuzzy_div` is redefined.

### CODE REVIEW

**Comment by Freakwill** [comment]
Thank you for your review. meshgrid(... , sparse=True) is a little faster, but meshgrid(...) not, another recommended method is np.repeat witch is also faster and produces matrices instead of sparse ones.

**Comment by JDWarner** [comment]
I'm perfectly happy using sparse intermediate matrices so long as they're transparent and internal, which as far as I can tell they are (reduced back to 1d for outputs).  Using meshgrid like you have here also has the advantage of making the code more readable and considerably less complicated.

From a technique perspective, no concerns.

**Comment by JDWarner** [comment]
@Freakwill do you have the time to make the small tweaks?

**Comment by JDWarner** [comment]
Ping @Freakwill - do you have the time to tweak the docstrings?

**Comment by Freakwill** [comment]
It is my pleasure.

**Comment by JDWarner** [comment]
I suspect a tab snuck in on the failing line. Looks great otherwise!

**Comment by JDWarner** [comment]
Superseded by #187, closing.

**Pull request closed without merging**
