### PR TITLE
Update Python support.

### PR DESCRIPTION
**Pull request by wouter-vdb**
Drop support for CPython <3.5 and add support for CPython 3.7-3.8. Note that OrderedDict is supported in PyPy >=2.2 and is therefore dropped as well.

### CODE REVIEW

**Comment by JDWarner** [comment]
I'm very impressed with the work you're doing here @wouter-vdb, thank you!

Historically we kept the Py2.x branch around because I know some people use this on systems with limited hardware or embedded and infrequently updated OSes.  However, I'm now comfortable dropping Python 2.x since NumPy just cut their first 3.x only release.

Do you feel this is complete and ready for review/merge, or do you have additional tweaks planned?

**Comment by wouter-vdb** [comment]
Thanks for the thumbs-up. Also note that Python 2 is EOL and won't even receive security fixes.

**Comment by wouter-vdb** [comment]
I keep on encountering things to remove/update. I'll drop a note here when I believe it's "done".

**Comment by wouter-vdb** [comment]
May I enforce flake8 in the Travis tests (excluding `test_*`)?

**Comment by wouter-vdb** [comment]
OK, I believe this PR is complete and ready for review/merge.

**Review by JDWarner — APPROVED** [review]
This looks fantastic, thank you for your thorough stylistic review/update and clean-up @wouter-vdb!  Thanks also for correcting a number of mild typos throughout the documentation.

**Pull request merged**
