### PR TITLE
Minor point release - 0.3.1

### PR DESCRIPTION
**Pull request by JDWarner**
This minor point release brings a significant new feature and minor fixes/compatibility enhancements:

Major feature:

* Arrays are now accepted as system inputs; all inputs must have the same shape.  The output matches this shape.  This is dramatically more computationally efficient for repeated runs on existing data - within the limits of your system memory. (see #141)

Minor fixes

* Fixed the mathematical definition of `skfuzzy.gaussmf`; this is a potentially breaking change but the results are now correct (see #147)
* NetworkX 2.0 forward compatibility (see #149 and #150)
* Improve and harmonize the `.view()` methods in `skfuzzy.control` (see #142 and #148)
* Update examples to use the above

### CODE REVIEW

**Comment by JDWarner** [comment]
This release is now live on PyPi, you can update to the new version with

`pip install --upgrade scikit-fuzzy`

**Comment by walzwerk** [comment]
Wow, that sounds very promising! :)
Unfortunately, the upgrade does not work with pip (nor conda) on my Anaconda ... :(
grafik

**Comment by JDWarner** [comment]
@walzwerk your pip fails before it's able to make a HTTP connection to PyPi; something is wrong there.  I suspect you can't `pip install` _anything_.

Scikit-Fuzzy is best installed via pip, because it is pure Python and has light dependencies with quite strong backwards compatibility.

**Comment by andrebelem** [comment]
Has anyone created an example or test for array input, as per this branch? I couldn't find in the documentation how this should work.

**Pull request merged**
