### PR TITLE
Fix lambda_cut with lcut=1 and add lambda_cut_boundaries function.

### PR DESCRIPTION
**Pull request by JDWarner**
Satisfies #48 - take a look @pbreach!

A fast and efficient method to detect an arbitrary number of cuts was simple to implement with convolution, then slightly tricky to make robust at edges. Symmetric padding by two elements should not materially affect the runtime of this routine.

This implementation **only** reports boundaries *that actually cross the lambda cut value within the provided membership function*. If one edge of a membership function was 0.3, a lambda cut value of 0.2 would not report the final value as a boundary. Put differently, it makes absolutely no assumptions about the membership function outside the provided discrete range.

### CODE REVIEW

**Comment by JDWarner** [comment]
Now `skfuzzy.image.pad` is used for array padding instead of `np.pad`, to enable backwards compatibility with NumPy < 1.7.x

Should make Travis happy.

**Comment by pbreach** [comment]
Nice! Looks good. I tried it out with tri,sig,trap, and gauss membership functions and the results are what I would expect. However, in the case of tri or gauss membership functions 2 values are returned for a lambda cut of 1 (which makes sense given the natue of the interpolation, however they are duplicate values), and in sig, one value is returned for a lambda cut of 0.5 (also makes sense given the nature of the membership function). 

I think this is ready to be merged, but In the future we could be more consistent in that either 2 values are returned for all cases (duplicate or not), or if duplicate values occur (in the tri and gauss membership function for a lambda cut of 1) then the first value is returned.

If I had to choose I would lean towards returning two values for any `lambda_cut_boundaries` for the sake of consistency. What do you think?

**Comment by JDWarner** [comment]
@pbreach Thanks for testing. I think I'll revise this once more to remove the degenerate double points with `np.unique` before returning; that behavior was not desired.

The problem with requiring two returns is twofold. Complicated membership functions with a lower peak and higher plateau *should* return exactly three crossings if the peak is encountered exactly. If a membership function has an edge between 0 and 1, should the edge be included? Or should the membership function be considered to continue at that value for the rest of the universe variable?

This is tricky. As currently designed, I pad via extension. This guarantees no transitions will occur exactly at the boundaries - unless the boundary is set exactly to the lambda cut value. However, if there are strong opinions for another implementation, I'm open to them.

**Comment by pbreach** [comment]
Okay `np.unique` sounds like a good solution for this. Good point on the two returns, I was thinking of only convex sets but more complicated membership functions would give some problems as you mentioned. It seems that lambda cuts and their boundaries are only really well defined for convex sets, but at least if a user encounters this problem they will be able to see how many boundaries they get and choose what to do in that case.

Edges seem tricky as well, but I think what you have is good. Matlab doesn't seem to have a function for this so I'm not sure if there's anything to compare to for this case. I think anything we do here is a step in the right direction IMO.

**Comment by JDWarner** [comment]
@pbreach thanks for your input. If anyone ends up really needing different edge behavior, that could be added in the future with a backwards-compatible kwarg. I do think this is the correct default behavior which doesn't make any assumptions.

Just added the `np.unique` fix along with a test to ensure the degenerate case is working as intended. Also expanded the docstring note.

**Pull request merged**
