### PR TITLE
DOC: Update pythonhosted documentation

### PR DESCRIPTION
**Pull request by jsexauer**
This addresses some of #77 

Please review and change as needed.  Especially need to double-check the links between the two new pages are done correctly.  Also, not sure how to actually publish to pythonhosted's website.

### CODE REVIEW

**Comment by JDWarner** [comment]
Right now I'm the owner of skfuzzy on pypi; all that's needed is to upload a zipped archive which unpacks with `index.html` in the root on the admin page.

**Comment by JDWarner** [comment]
Overall this looks great! I'll kick the tires later this afternoon, including those links.

I wonder if we should retain the prior example, perhaps calling it "the hard/bad way" while directing users to the new API? Some users might really appreciate knowing how to do this manually, including for classwork.

**Comment by JDWarner** [comment]
Moving forward, making a separate repo for the docs hosted by github with auto-push from successful test builds is probably the right path.

**Comment by jsexauer** [comment]
Yea I think retaining the old code is a good idea.

**Comment by JDWarner** [comment]
@jsexauer made a PR against this branch for you.

**Comment by jsexauer** [comment]
Merged.  @JDWarner I assume you'll take care of migrating this to python hosted?

**Comment by JDWarner** [comment]
Yup, that's next on my list after #85 gets merged too.

**Pull request merged**
