### PR TITLE
fix(imports): pass matplotlib ImportError

### LINKED ISSUE #246: Importing skfuzzy.control fails due to matplotlib absence
While `matplotlib` is _not_ a dependency for `skfuzzy` (although it is for the docs). Is necessary when importing `skfuzzy.control`.

This could be easily solved replacing `import matplotlib.pyploy as plt` with:

```python
try:
    import matplotlib.pyplot as plt
except ImportError:
    pass
```

If it's ok, i could do this changes :+1:

### PR DESCRIPTION
**Pull request by MarcoMiretti**
Matplotlib is not a dependency, therefore its absence shouldn't cause problems
building or during execution.
Is possible to run into this problem specially on limited hardware.

The following changes have been made:
replace,
```python
import matplotlib.pyplot as plt
```
for,
```python
try:
    import matplotlib.pyplot as plt
except ImportError:
    pass
```

This changes allow the setup and use without matplotlib.
Closes #246

### CODE REVIEW

**Comment by JDWarner** [comment]
Apologies for the delay in review, @MarcoMiretti.  COVID is presently absorbing most of my time.

A couple changes are needed:
* Could you please revert all changes in `docs`?  Those are required and using this motif will simply cause errors later.  The docs are separate and not imported with the package.  Matplotlib is a doc build requirement.
* We need conditional logic branching in `FuzzyVariableVisualizer`.  Simply bypassing the import like this will cause uninformative errors if `.view()` is ever called thanks to `plt` not being defined.  In the try/except consider defining a variable like `matplotlib_present = [True/False]` and then run a test script which calls `.view()` and branch on this variable at the appropriate place in the `__init__`.  The goal is to send the user an informative error message saying matplotlib is not found, so `.view()` is unavailable rather than letting it fail.

**Comment by MarcoMiretti** [comment]
@JDWarner no need to apologize. Thanks for your collaboration during this pandemic.

Regarding the changes, both are absolutely reasonable. I will take care of them in the following days and update the PR.

**Comment by JDWarner** [comment]
Hi @MarcoMiretti, sending a gentle ping - I know everyone has many things on their minds these days.  Your proposed improvement is welcome.

If reverting the docs changes is too frustrating as it's all in a single commit, you could copy your changes outside `docs` into a new branch with a new PR.

**Comment by MarcoMiretti** [comment]
Josh, sorry for my absence. I reverted the changes in the docs and plan to do the tests for this change during these days.

**Comment by MarcoMiretti** [comment]
Hi @JDWarner, two questions here regarding the tests:

- I didn't write the tests yet, but there is an environment failing (python3.6), throwing some import error with `numpy.testing.decorators` Should i pay attention to this?

- About the tests for this fix: Should i create versions of the current environments without `matplotlib`, and then do some kind of logic inside `script` to run my specific test in said environvents?

**Comment by MarcoMiretti** [comment]
> Hi @JDWarner, two questions here regarding the tests:
> 
>     * I didn't write the tests yet, but there is an environment failing (python3.6), throwing some import error with `numpy.testing.decorators` Should i pay attention to this?
> 
>     * About the tests for this fix: Should i create versions of the current environments without `matplotlib`, and then do some kind of logic inside `script` to run my specific test in said environments?

Hi @JDWarner,

- The tests now pass when i added your last changes to this branch.
- The second question still remains, ¿Should i create new test environments without `matplotlib` support?

**Comment by MarcoMiretti** [comment]
Hi @JDWarner,

Have you reviewed this? Can i help clarifying it somehow? :)

**Comment by JDWarner** [comment]
Thanks @MarcoMiretti - after long delay I will finally merge this!

**Pull request merged**
