### PR TITLE
FEAT: High-level fuzzy control system API

### PR DESCRIPTION
**Pull request by JDWarner**
This PR adds what many people (see #69, #66, and multiple posts on the mailing list) have asked for: a much improved framework to implement fuzzy systems from end to end. 

* One major new dependency: **networkx**.
* This API lives in `skfuzzy.control`, and primarily uses four classes
    * `Antecedent`
    * `Consequent`
    * `Rule`
    * `ControlSystem`

Presently it's functional but sill a WIP. It is stable enough for other people to kick the tires at this point. If there are things missing you would like to see, speak up!

The major benefit is a simple yet very powerful API to build a fuzzy system, from input/antecedents to output/consequents, including all of the rules. Documentation will improve over the course of this PR, but here is the tipping problem implemented with this PR:

``` python
import numpy as np
import skfuzzy as fuzz

# New Antecedent/Consequent objects hold universe variables and membership functions
quality = fuzz.Antecedent(np.arange(0, 11, 1), 'quality')
service = fuzz.Antecedent(np.arange(0, 11, 1), 'service')
tip = fuzz.Consequent(np.arange(0, 26, 1), 'tip')

# Auto-membership function population is possible with .automf(3, 5, or 7)
quality.automf(3)
service.automf(3)

# Custom membership functions can be built interactively with a familiar, Pythonic API
tip['poor'] = fuzz.trimf(tip.universe, [0, 0, 13])
tip['average'] = fuzz.trimf(tip.universe, [0, 13, 25])
tip['good'] = fuzz.trimf(tip.universe, [13, 25, 25])

# You can see how these look with .view()
quality.view()
service.view()
tip.view()

# Rule objects connect one or more antecedent membership functions with 
# one or more consequent membership functions, using 'or' or 'and' to combine the antecedents.
#   * rule1: "If food is poor OR services is poor, then tip will be poor
#   * rule2: "If service is average, then tip will be average
#   * rule3: "If service is good OR food is good, then tip will be good
rule1 = fuzz.Rule([quality['poor'], service['poor']], tip['poor'], kind='or')
rule2 = fuzz.Rule(service['average'], tip['average'])
rule3 = fuzz.Rule([service['good'], quality['good']], tip['good'])

# Create a new ControlSystem with these rules added
# Note: it is possible to create an empty ControlSystem() and build it up interactively.
tipping = fuzz.ControlSystem([rule1, rule2, rule3])

# Pass inputs to the ControlSystem using Antecedent labels with Pythonic API
# Note: if you like passing many inputs all at once, use .inputs(dict_of_data)
tipping.input['quality'] = 6.5
tipping.input['service'] = 9.8

# Crunch the numbers
tipping.compute()

# Output available as a dict, for arbitrary number of consequents
tipping.output

# Viewing the Consequent again after computation shows the calculated system
tip.view()
```

A lot shorter than [the old way,](http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem.html) and more intuitive!

### CODE REVIEW

**Comment by mohammedaljawad** [comment]
Thank so much for the example. Can you please explain, how possible to add those four classes: 

    Antecedent
    Consequent
    Rule
    ControlSystem

I tried to redownload the package and reinstall it but it didn't work. 
Regards 
Mohammed

**Comment by JDWarner** [comment]
@mohammedaljawad this currently requires Git and a development version as it is still being improved. If you don't have Git, you'll need that. Once you have Git, these commands run in order in a terminal will do the job:

``` bash
git clone https://github.com/scikit-fuzzy/scikit-fuzzy.git
cd scikit-fuzzy
git fetch
git checkout fuzzycontrolsystem
python setup.py develop
```

After that, restart your preferred Python shell and run `import skfuzzy; skfuzzy.__version__`. You should see "0.2dev" instead of "0.1.3", and these features will be available.

**Comment by mohammedaljawad** [comment]
Thanks a lot.
I just got this message when I run the line before the last:

 git checkout fuzzycontrolsystem
error: pathspec 'fuzzycontrolsystem' did not match any file(s) known to git.
Regards
Mohammed

**Comment by JDWarner** [comment]
```
git remote add JDWarner https://github.com/JDWarner/scikit-fuzzy.git
git pull JDWarner fuzzycontrolsystem
```
There will be a merge commit you need to approve by pressing Shift+Z twice. Then

```
python setup.py develop
```

**Comment by mohammedaljawad** [comment]
Thank you so much Dr. Josh,

I just get that:

python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 106, in <module>
    check_requirements()
  File "setup.py", line 55, in check_requirements
    % ((package_name, ) + min_version))
ImportError: `networkx` version 1.9 or later required.

**Comment by JDWarner** [comment]
Yes, you will need to install networkx. It is now a dependency.

**Comment by mohammedaljawad** [comment]
Dear Dr. Josh,
Thank you so much, I am really so indebted to you.
Regards
Mohammed

**Comment by JDWarner** [comment]
@mohammedaljawad Please report back your experience using this, especially including any problems!

**Comment by mohammedaljawad** [comment]
Sure sir, I am so glad to do that. But I can't find that, is there any
specific comment place that I can use.
Regards

**Comment by JDWarner** [comment]
This is the appropriate place.

**Comment by mohammedaljawad** [comment]
Hi, 
thanks for your help in advance. 
I customized the tutorial and now it supports four inputs with three intervals and one output with five intervals. And I got this message:

Traceback (most recent call last):
  File "mine.py", line 62, in <module>
    trusting.compute()
  File "/home/mohammed/scikit-fuzzy/skfuzzy/control/controlsystem.py", line 290, in compute
    consequent.compute()
  File "/home/mohammed/scikit-fuzzy/skfuzzy/control/antecedent_consequent.py", line 190, in compute
    self.output = defuzz(self.universe, self.output_mf, mode)
  File "/home/mohammed/scikit-fuzzy/skfuzzy/defuzzify/defuzz.py", line 132, in defuzz
    assert tot_area != 0, 'Total area is zero in defuzzification!'
AssertionError: Total area is zero in defuzzification!

**Comment by JDWarner** [comment]
For the first problem, it's either a real bug or a set of inputs that is outside the bounds of a sparse rule set. I need more info to know for sure; can you post your test script?

For the second problem, the automatic membership function creation works - the issue is in the visualization script. After you get that error, what is the result of `trust.output`? It should be `None` which would avoid execution of that problem line. I'll look into this further tonight.

**Comment by mohammedaljawad** [comment]
Thanks a lot. Below is my code: 

import numpy as np
import skfuzzy as fuzz

# New Antecedent/Consequent objects hold universe variables and membership
#functions
hs = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'hs')
prf = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'prf')
abt = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'abt')
cl = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'cl')
tr = fuzz.Consequent(np.arange(0, 1.1, 0.1), 'tr')

# Auto-membership function population is possible with .automf(3, 5, or 7)
hs.automf(3)
prf.automf(3)
abt.automf(3)
cl.automf(3)
tr.automf(5)


# Custom membership functions can be built interactively with a familiar,
# Pythonic API
"""tr['low'] = fuzz.trimf(tr.universe, [0, 0, 0.25])
tr['mediumlow'] = fuzz.trimf(tr.universe, [0, 0.25, 0.5])
tr['medium'] = fuzz.trimf(tr.universe, [0.25, 0.5, 0.75])
tr['midiumhigh'] = fuzz.trimf(tr.universe, [0.5, 0.75, 1])
tr['high'] = fuzz.trimf(tr.universe, [0.75, 1, 1])
"""


# You can see how these look with .view()
hs.view()
prf.view()
abt.view()
cl.view()
tr.view()

# Rule objects connect one or more antecedent membership functions with
# one or more consequent membership functions, using 'or' or 'and' to combine
# the antecedents.
#   * rule1: "If food is poor OR services is poor, then tip will be poor
#   * rule2: "If service is average, then tip will be average
#   * rule3: "If service is good OR food is good, then tip will be good
rule1 = fuzz.Rule([hs['poor'], prf['poor'], abt['poor']
, cl['poor']], tr['poor'] ,kind='or')
rule2 = fuzz.Rule([hs['average'], prf['average']
, abt['average'], cl['average']], tr['average'])
rule3 = fuzz.Rule([hs['good'], prf['good'], abt['good']
, cl['good']], tr['good'])



# Create a new ControlSystem with these rules added
# Note: it is possible to create an empty ControlSystem() and build it up
#interactively.
tring = fuzz.ControlSystem([rule1, rule2, rule3])

# Pass inputs to the ControlSystem using Antecedent labels with Pythonic API
# Note: if you like passing many inputs all at once, use .inputs(dict_of_data)
tring.input['hs'] = 0.9
tring.input['prf'] = 0.9
tring.input['abt'] = 0.9
tring.input['cl'] = 0.9

# Crunch the numbers
tring.compute()

# Output available as a dict, for arbitrary number of consequents
tring.output

# Viewing the Consequent again after computation shows the calculated system
tr.view()

a=input("HellO")

**Comment by mohammedaljawad** [comment]
I tired this: 
"""tr['low'] = fuzz.trimf(tr.universe, [0, 0, 0.25])
tr['mediumlow'] = fuzz.trimf(tr.universe, [0, 0.25, 0.5])
tr['medium'] = fuzz.trimf(tr.universe, [0.25, 0.5, 0.75])
tr['midiumhigh'] = fuzz.trimf(tr.universe, [0.5, 0.75, 1])
tr['high'] = fuzz.trimf(tr.universe, [0.75, 1, 1])
"""
but it didn't work. 
Then I used the automated one.

**Comment by JDWarner** [comment]
@mohammedaljawad The first issue was a real bug, now fixed - `automf` cleared the output incorrectly for Consequents. This was _also_ the root cause of the second issue. See how it works now.

**Comment by mohammedaljawad** [comment]
Thanks a lot. 
I got this message : 
fatal: Not a git repository (or any of the parent directories): .git

**Comment by JDWarner** [comment]
You have to run that command in the scikit-fuzzy directory tree.

**Comment by mohammedaljawad** [comment]
Shift+Z Shift+Z ?

**Comment by JDWarner** [comment]
Yes, as before.

**Comment by mohammedaljawad** [comment]
Thanks a lot. 
I got two of them with trapezoidal shape, however, I should get them Triangular shape

**Comment by JDWarner** [comment]
That's because your universe variable isn't high enough resolution. If the peaks aren't included as valid points, when matplotlib connects the dots, you'll see trapezoids.

**Comment by mohammedaljawad** [comment]
I already set the variables of all membership functions. Sorry, I don't get that. Is there any reference or explanation for that.

**Comment by mohammedaljawad** [comment]
By the way I implemented that on Matlab and I didn't get this issue.

**Comment by JDWarner** [comment]
There is no issue, it's in the visualization. 

Think about this: If your universe only has points at [0, 2.5, 5, 7.5, 10], what happens when you want a triangular membership function starting at 2.5 and ending at 10 **with a peak at 6**? Membership functions exist only where their universes are defined, so there is no way to have a true peak between points in the universe.

This means you must choose your universe to be high enough resolution to include your peaks.

I've no idea what Matlab is doing; I don't use or look at their code. Best guess is they may automatically upsample sparse universes under the hood.

**Comment by mohammedaljawad** [comment]
Thank you so much for your help. But can I get some references talk deeply about that. Since, I need to justify every single step in my research.

**Comment by JDWarner** [comment]
This is self-evident, it is clear enough that it wouldn't be publishable. Make the example I just sketched out above with fuzz.trimf and plot it a few times to convince yourself.

**Comment by mohammedaljawad** [comment]
thanks a lot, sure I'll do

**Comment by mohammedaljawad** [comment]
Mr. Josh, may I know please how can I get the result of : 
tring.compute()

I mean the output value. 
thanks in advance

**Comment by JDWarner** [comment]
The output(s) from the system are available in the `FuzzySystem.output` variable as an OrderedDict. The label of each Consequent is the key, and it's attached to the resulting value. 

Inputs can then be changed and `.compute()` will update the output variable, with only the minimal amount of computations needed.

**Comment by mohammedaljawad** [comment]
Hi Mr.Josh, 
thanks a lot for your help. I got the output. Which method should I use to fuzzify it.

**Comment by JDWarner** [comment]
Test suite and some Travis-CI build improvements now also included.

@mohammedaljawad I'm unsure what you mean. The usual purpose of a fuzzy system is to take crisp inputs and map them to crisp outputs, through a fuzzy system. When you _have_ the output, generally you do not need or want to fuzzify it again.

**Comment by mohammedaljawad** [comment]
Thanks a lot for your help and support. 
Indeed, I just need to verify the result manually. I mean mathematically. Is there anyway to do that. 
Thanks in advance.

**Comment by mohammedaljawad** [comment]
Dear Mr.Warner, 
I can't use more than three rules. I received this message when I want to add the fourth rule: 
Traceback (most recent call last):
  File "mine4.1.py", line 78, in <module>
    trusting.compute()
  File "/home/mohammed/scikit-fuzzy/skfuzzy/control/controlsystem.py", line 277, in compute
    *[s._id for s in self.graph.successors(mf)])
TypeError: add() takes exactly one argument (2 given)

**Comment by JDWarner** [comment]
@mohammedaljawad Thanks for the report, that was a real bug - I refactored that section and it should now be fixed.

**Comment by mohammedaljawad** [comment]
Not at all Mr.Warner, I am so thankful for your support and help all the time. 
How can I patch it?

**Comment by JDWarner** [comment]
Same as before:  `git pull JDWarner fuzzycontrolsystem` in the scikit-fuzzy directory tree.

**Comment by mohammedaljawad** [comment]
thanks a lot 
I have a queation about the "   ,kind='or'   "  which will be at the end of each rule. So, does that work for all expression? 
and what if I have "and" and "or" in different places in one expression.

**Comment by JDWarner** [comment]
Initially, for simpler testing, only a single modifier was supported for each rule, which applies to all antecedents. I plan to implement the ability to set these arbitrarily for each combination of rules, but haven't found an API I was happy with.

Can you post an example of a complicated rule? Some can be decomposed into a set of simpler rules that work within this framework, but not all.

Then, let's think about the API. How would you *like* to input such a rule?

**Comment by mohammedaljawad** [comment]
for example: 
IF (cost is low AND durability is high OR brand is good) THEN decision=highlyaccepted

**Comment by mohammedaljawad** [comment]
Dear Mr. Warner, 
I got this message after adding all my rules which are only nine.
Traceback (most recent call last):
  File "mine4.py", line 105, in <module>
    trusting.compute()
  File "/home/mohammed/scikit-fuzzy/skfuzzy/control/controlsystem.py", line 293, in compute
    consequent.compute()
  File "/home/mohammed/scikit-fuzzy/skfuzzy/control/antecedent_consequent.py", line 179, in compute
    self.output = defuzz(self.universe, self.output_mf, mode)
  File "/home/mohammed/scikit-fuzzy/skfuzzy/defuzzify/defuzz.py", line 132, in defuzz
    assert tot_area != 0, 'Total area is zero in defuzzification!'
AssertionError: Total area is zero in defuzzification!

**Comment by JDWarner** [comment]
That particular rule can be decomposed into two rules, which are equivalent to the original:

IF cost is low AND durability is high, THEN decision is highlyaccepted.
IF brand is good, THEN decision is highlyaccepted.

However, if the original switched the 'and' with the 'or', decomposition would be impossible. For that case I need API ideas.

I'll look into the error, though may need the full file to understand what's going on. Regardless, the error message could definitely be more helpful.

**Comment by mohammedaljawad** [comment]
This is the code:
import numpy as np
import skfuzzy as fuzz

# New Antecedent/Consequent objects hold universe variables and membership
#functions
hs = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'hs')
prf = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'prf')
abt = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'abt')
cl = fuzz.Antecedent(np.arange(0, 1.1,0.1), 'cl')
tr = fuzz.Consequent(np.arange(0, 1.1, 0.1), 'tr')

# Auto-membership function population is possible with .automf(3, 5, or 7)
hs.automf(3)
prf.automf(3)
abt.automf(3)
cl.automf(3)


# Custom membership functions can be built interactively with a familiar,
# Pythonic API
tr['low'] = fuzz.trimf(tr.universe, [0, 0, 0.25])
tr['mediumlow'] = fuzz.trimf(tr.universe, [0, 0.25, 0.5])
tr['medium'] = fuzz.trimf(tr.universe, [0.25, 0.5, 0.75])
tr['mediumhigh'] = fuzz.trimf(tr.universe, [0.5, 0.75, 1])
tr['high'] = fuzz.trimf(tr.universe, [0.75, 1, 1])


# You can see how these look with .view()
hs.view()
prf.view()
abt.view()
cl.view()

# Rule objects connect one or more antecedent membership functions with
# one or more consequent membership functions, using 'or' or 'and' to combine
# the antecedents.
#   * rule1: "If food is poor OR services is poor, then tip will be poor
#   * rule2: "If service is average, then tip will be average
#   * rule3: "If service is good OR food is good, then tip will be good
rule1 = fuzz.Rule([hs['poor'], prf['poor'], abt['poor']
, cl['poor']], tr['low'] ,kind='and')
rule2 = fuzz.Rule([hs['poor'], prf['poor']
, abt['poor'], cl['good']], tr['mediumhigh'] ,kind='and')
rule3 = fuzz.Rule([hs['average'], prf['average'], abt['poor']
, cl['poor']], tr['mediumhigh'])
rule4 = fuzz.Rule([hs['average'], prf['poor'], abt['average']
, cl['poor']], tr['medium'] ,kind='and')
rule5 = fuzz.Rule([hs['average'], prf['average'], abt['good']
, cl['poor']], tr['high'] ,kind='and')
rule6 = fuzz.Rule([hs['good'], prf['poor'], abt['good']
, cl['poor']], tr['mediumhigh'] ,kind='and')
rule7 = fuzz.Rule([hs['good'], prf['good'], abt['poor']
, cl['poor']], tr['mediumhigh'] ,kind='and')
rule8 = fuzz.Rule([hs['poor'], prf['poor'], abt['good']
, cl['poor']], tr['mediumlow'] ,kind='and')
rule9 = fuzz.Rule([hs['good'], prf['average'], abt['poor']
, cl['poor']], tr['mediumhigh'] ,kind='and')


# Create a new ControlSystem with these rules added
# Note: it is possible to create an empty ControlSystem() and build it up
#interactively.
tring = fuzz.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])

# Pass inputs to the ControlSystem using Antecedent labels with Pythonic API
# Note: if you like passing many inputs all at once, use .inputs(dict_of_data)
tring.input['hs'] = 0.3
tring.input['prf'] = 0.3
tring.input['abt'] = 0.3
tring.input['cl'] = 0.3

# Crunch the numbers
tring.compute()

# Output available as a dict, for arbitrary number of consequents
tring.output

# Viewing the Consequent again after computation shows the calculated system
tr.view()


a=input("HellO")

**Comment by mohammedaljawad** [comment]
Dear Dr.Warner, 
I matched the result of the python program with Matlab and I can see there is a big difference sometimes between the results. Can you help me please. 
Regards

**Comment by JDWarner** [comment]
@mohammedaljawad That script runs without error, for me, yielding a result showing `tring.output` is 0.5. Is the expected result not 0.5?

**Comment by mohammedaljawad** [comment]
Thank you Dr.Warner for your reply. Indeed, I just tested the program with different input values and I found when I feed the program with (0,0,0,0) the result will be 0.17222; then I check how the Matlab will deals with these values and I found the result is 0 . The other issue that I found the rules can affect each other; because the result of (0,0,0,0) is 0.05555 (which is nearly zero) if I use only the first seven rules, but after using the eighth rule; the result will turn to 0.17222. As I know with Mamdani the rules will never affect each other. I hope I was able to explain the issue clearly. 
Regards

**Comment by JDWarner** [comment]
I strongly suspect the Matlab variant is defined differently, or includes an 'and' modifier which isn't included here in rule 8. Because as defined, this is working as intended.

Regarding rule independence, remember the output from the system is different from the contribution of each rule. The system output obviously will change, but each individual rule's contribution remains independent.

**Comment by mohammedaljawad** [comment]
I strongly agree with you. But, I just need the mathematical model which I can use to do the manual calculation. In this case I'll get the evidence and nobody will ask about comparing the result with any other API. I hope I can get that with a simple example.

**Comment by JDWarner** [comment]
Follow [the original tipping problem example](http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem.html), which yields the exact same result as my script in the original post using the new interface. That's as manual as it gets, and you can compare the results. If you need to know the code behind any of the functions, it's available behind the source links in [the API docs](http://pythonhosted.org/scikit-fuzzy/api/api.html).

**Comment by mohammedaljawad** [comment]
Dear Dr.Warner, I am really so thankful for your help. I'll use that but I hope I can get a small example with the mathematical model. Even, a small example with two inputs and one output and I can expand it to four inputs and one output. 
Regards

**Comment by jsexauer** [comment]
Dr Warner,

This is a cool feature, but I see two potential issues.  How would I address them?

- How do I negate one of the antecedents?
- How could I chain consequences (ie, IF Consequence A and Antecedent B THEN consequence C)

Thanks!

**Comment by JDWarner** [comment]
@jsexauer 

For negation, at present this can be accomplished by using `skfuzzy.fuzzy_not` (or just `1. - mf`) prior to initialization of the fuzzy Antecedent or Consequent. If you have ideas on an API which would allow this to be applied at time of computation, I'm all ears! It can be done, I just lack an API I'm satisfied with.

For chaining consequents, that is an interesting idea. When I designed this I was thinking of single level systems, rather than multi-level systems where the outputs of one level are used as inputs to the next. Again, this _is_ possible - I just haven't given thought to an ideal API.

Off the top of my head, a refactor converging Antecedent and Consequent back to a single FuzzyVariable class might be needed. Depending on their position in the graph, they could act appropriately. (Obviously, this glosses over some major implementation details).

If you have thoughts about how you or a user _would like to use this_, I'd love to hear them. I really need to have a solid API in mind before diving in.

**Comment by JDWarner** [comment]
Thanks to @jsexauer for an excellent overhaul of the framework! I'm merging this in a broken state so we can move forward, hammering out the API and test suite in separate PRs.

**Comment by nilayrox18** [comment]
hello Mr. Warner. i am posting my code and error message please solve it for me i need you help.
import numpy as np
import skfuzzy as fuzz


quality = fuzz.Antecedent(np.arange(0,11,1),'quality')
service = fuzz.Antecedent(np.arange(0,11,1),'service')

tip = fuzz.Consequent(np.arange(0,26,1),'tip')


quality.automf(3)
service.automf(3)
tip.automf(3)

quality.view()
service.view()
tip.view()

rule1 = fuzz.Rule(quality['poor'] | service['poor'],tip['poor'])
rule2 = fuzz.Rule(quality['good'] | service['good'],tip['good'])

tip_cnt = fuzz.ControlSystem([rule1, rule2])

tipp = fuzz.ControlSystemSimulation(tip_cnt)

tipp.input['quality'] = 5
tipp.input['service'] = 5

tipp.compute()

print(tipp.output)

error msg is: 
Traceback (most recent call last):
  File "C:\Users\DarkEvill\Desktop\ex3456.py", line 29, in <module>
    tipp.compute()
  File "C:\Python34\lib\site-packages\scikit_fuzzy-0.2dev-py3.4.egg\skfuzzy\control\controlsystem.py", line 147, in compute
    if antecedent.terms.values()[0].membership_value[self] is not None:
TypeError: 'ValuesView' object does not support indexing

**Comment by jsexauer** [comment]
@nilayrox18 I am unable to reproduce your issue give the code above in python 2.7.  However, this does appear to be an issue in Python 3 due to the fact that `OrderedDict` returns a ValuesView instead of new list.  I will address in a seperate PR.

**Comment by Raghavaraman** [comment]
hey i am trying to use the control module but am getting "AttributeError: 'module' object has no attribute 'Antecedent'" what should i do to make this attribute work??

**Comment by JDWarner** [comment]
@Raghavaraman The new API is merged in to the 0.2dev development branch in anticipation of the 0.2 release, however, that release has not yet happened. The new control system API still needs a few tweaks yet (working on it!).

However, we welcome you to experiment with the new control system API! Simply clone this repository and run `python setup.py develop` in the root directory - you'll then have version 0.2dev and can keep up to date running `git pull origin master` periodically. 

We'd like as many people as possible to try it out before release, so please do!

**Comment by Raghavaraman** [comment]
thank you sir, i used git commands ava. in linux derbian based system and when i try to import the skfuzzy into python it says no lib present. do you have any suggestion as to what went wrong?

P.S i had to use sudo command to run the setup .

**Comment by JDWarner** [comment]
@Raghavaraman Probably two issues.

First, if you have to run sudo generally there will be problems. Permissions on *NIX create issues with Python because Python compiles .py files to .pyc files at runtime. If these files can't be written, it's an issue. A good rule is any time you download a new Python package manually (without using the system apt-get or yum), put it in your current user folder and run `python setup.py develop` instead of `python setup.py install`. 

The `develop` command keeps it there, where you have permission, updating only your PYTHONPATH. The `install` command tries to install it to your Python's site-packages, which may not be under your control.

The second possibility is that you may not have run `python setup.py develop`. If you didn't, then the package is unknown to your Python installation and it won't be able to import it.

**Comment by ManolisCh** [comment]
Hi and thanks for this very promising fuzzy package!

I find the new API very helpful and easy to use for quickly building fuzzy systems. However I haven't found yet how to have control (with the new API) over a few things such as, the fuzzy operators and the deffuzification methods to be used.

I was wondering if this is something that hasn't implemented yet or something that I have missed given I am new to fuzzy and python?

**Comment by JDWarner** [comment]
Hi @ManolisCh, that's a great question. We've built some internal functionality around these goals, but I don't think it is yet exposed. Mainly because we haven't yet found a simple, powerful way to do so. 

This particular PR is already merged, and the discussion is lengthy, so I'm going to move your suggestion to a separate Issue as a feature request. 

I fully expect we will make this functionality available, but we want to make sure we do so in the best way possible. Within the current framework, how you would _like_ to control these options? What do you see as the most elegant and intuitive way to control them?

**Comment by ManolisCh** [comment]
Thanks for your quick answer! I will reply once I got some more experience using scikit-fuzzy in the newly  open feature request.

**Pull request merged**
